### ISSUE TITLE
Expose Camera HUD font size to preferences

### ISSUE THREAD

**Issue by garyritchie** [ubisoft/shotmanager#24]
https://github.com/ubisoft/shotmanager/blob/8e351fd46abfa94b971f4661cb9ba8904c0f899e/shotmanager/overlay_tools/viewport_camera_hud/camera_hud_bgl.py#L100

On a 4k monitor with 150% scaling set in Windows Display preferences, the `font_size` setting of `10` is a wee bit too small for my old eyes. Blender's UI scaling also set to 1.0 but adjusting did not affect HUD text size.

**Comment by werwack** [comment]
Hi @garyritchie,
This is a good point. Annoying, hum? I agree.
It was planned for a while but since you asked... It is in the [latest release, v1.7.16](https://github.com/ubisoft/shotmanager/releases/tag/v1.7.16). Can you check and let me know if everything is fine?
BTW I also fixed an issue: shot names are not displayed anymore for hidden cameras.

**Comment by garyritchie** [comment]
This is great, thanks @werwack ! Works well with Blender 3.1.2.
