### ISSUE TITLE
Title Change

### ISSUE THREAD

**Issue by OtherRealms** [ubisoft/shotmanager#36]
Hi I'm the author of Shot Manager addon for Blender (2019). My addon is a paid product ([Blender Market](https://blendermarket.com/products/shot-manager)) of the same name and with similar functionality which I have dedicated an immense amount of time in developing. I am using a request as I'm unable to find any relevant contact details. 

I like to request a modification to the addon name. Please consider that it uses exactly the same name as well as name set in bl_info and interface, This similarity in names is directly affecting my sales as potential customers are not aware that they are two different add-ons. While there is no legal necessity to change the name, I ask in the spirit of fairness, that you consider the background of existing add-ons and small businesses, which play a major role in the Blender community.

Minimal name suggestion : Ubisoft Shot Manager
I understand that a name without 'Shot Manager' in it would take considerable time to propagate the changes everywhere, but anything you could do to increase the distinction would be greatly appreciated.

To discuss further, I can be contacted at contact@pablotochez.com
thanks,
Pablo TA

**Comment by werwack** [comment]
Hi Pablo,

Well, you are at the right place for the contact I believe.
I'm the original designer of Ubisoft Shot Manager, I was one of the 2 developers when we deployed it in production and I'm the current maintainer.

I perfectly understand you request. I do apologize for this naming similarity and I sincerely regret this has an impact on your business. I must say I am not really surprised we eventually have this discussion because I've heard about your add-on... But I discovered its existence only a few months ago 😕

The add-on we developed was based on an idea I had 15 years ago while working for advertisement and that I implemented in 3dsMax. Basically it was to, hum, manage shots. In other words, and that's also the 2 key concepts of our add-on, to have a notion of shots and to be able to play them in a non-linear way in real-time in the viewport.
When we started working on it we were quick in looking at what existed on the market since I had a very clear idea of were I wanted to go with it. I didn't see your add-on at that time and we went to this name cause it was describing well the purpose of the tool. This was 2,5 years ago.
Then the add-on was open-sourced last summer, then we had our first users, then we started to write the documentation... And then I fall onto a video presenting your add-on. 😶 To be honest, I've never been beyond that video to avoid being "inspired" by other approaches and also in the idea of respecting original ideas (in a way that's what you called the "spirit of fairness").

I had a discussion with someone about that at the Blender Foundation to see how to avoid as much as possible confusion for the users there. Clearly it was too much work for us to change the name, it was everywhere, not only in the code but on the GitHub, on links, etc. Too late. Best we could do was to communicate on it on the name, as you mentioned, "Ubisoft Shot Manager", what we did as much as possible. 

So... I'm really confused about the situation now. This was really not intentional.

Currently our add-on is referred to under this name in the documentation, on the repos, in the release packages, in the About window... Not on the title bar of the panel though, neither on the tabs. I will think about how I can introduce a better distinction there, but I'm also facing an issue of space to display all the relevant user information.

Regarding the name of the add-on as declared in the bl_info I guess we both have "name": "Shot Manager" ? 😓
Maybe I can change it, if it doesn't break the backward compatibility... 

**This discussion is opened, if anybody reading this has ideas and suggestions you are all very welcome to contribute.**

Julien

**Comment by OtherRealms** [comment]
Hi Julien, thanks for the info. 
It's quite possible that both addons were in development without knowledge of each other and I'm not suggesting there is any copying going on. It is of course an easy to think of name and intentionally so. I would have hoped that the name change would take place before being made Open Source alongside docs , web, videos as SM was well established on the web by that point. I was surprised by similarities when UbiSM was released but didn't notice any impact until more recently. 

As for what to do now, I'm not sure what backwards compatibility UbiSM supports, I'd imagine it means supporting older files using the addon, rather than reverting to older addon versions, so I don't imagine anything would be lost in terms of registered classes by changing the addon name and UI. Currently, I think its also not possible to have both addons installed.  

I hope there is a rather simple solution such as batch renaming 'Shot Manager' in the docs. Better yet, it would be something that wouldn't contain exactly the same search words, such as 'Shot Tools' or 'UbiSM'. Drastic, but I can only hope it is resolved sooner than later as it will only become more difficult in the future, plus there is the added flexibility on your end of not being a commercial product. 

I'm in the process of creating more tutorials for the 0.7 series using a professional voice artist but I really need confidence in knowing its worth the time. Having what could easily been seen as 'free version' has its undeniable appeal.

**Comment by werwack** [comment]
Hi Pablo,

From the investigation we did here it appeared that changing the add-on name in the bl_info has a small and very manageable impact on the deployment of our add-on. All the existing files are still fully compatible with the renamed version of the add-on.
We then changed the name of it to "Ubisoft Shot Manager" in the latest release. It should now then be possible to install both your add-on and ours at the same time in the same instance of Blender.
We also changed the name to "Ubisoft Shot Manager" in the title bar of the main panel.

Changing the name that is displayed in the tabs has, at the contrary, a deeper impact: the behavior, the UI and the consistency with our video tutorials are being affected. You said that we have an "added flexibility of not being a commercial product". In fact the add-on as it is being used internally in our productions. This is a considerable constraint we have to deal with. Hence the name on the tabs (Shot Mng) will not be modified. This may not be too much of an issue for you hopefully since, as far as I've seen, you don't seem to use tabs on your side.

At last I have the feeling that our add-ons are not really competing (well, except for the name 😕), in the way that yours seems very oriented towards rendering whereas our is for early production steps, namely storyboarding and previz. I'll try to be clear on that in our communications to minimize possible ambiguities. 

 I hope this goes into the direction you expected.

Julien

**Comment by OtherRealms** [comment]
Hi Julien,
thanks for spending time on this. I'm glad they might not be competing on the code level. I use the 'sm' prefix a lot so hopefully there aren't any overlapping classes or props. I might try to install both and see if there are any clashes. I'll have to see which tabs you are refering to. I agree that they are ultimately different addons as SM is more focussed on render management and hope that is continues to be conveyed. I'll let you know if there are any ui clashes etc. 
Cheers, 
Pablo

**Comment by werwack** [comment]
Hi Pablo,
There should not be conflicts in the operators nor tabs names, We are not using "sm" but "uas_" to prefix those entities. I'll double-check this.
We don't have plans to make custom rendering settings per shots at all, that is not the purpose of our add-on. I would like to improve a bit the rendering process though by adding a progress bar. That's not trivial to introduce in the current code so it is currently not a high priority. Do you have something like that on your side? Facing some issues there?

In the mean time I will improve the information stamped on the final images. The add-on Ubisoft Stamped Info we used so far has been completely integrated into Ubisoft Shot Manager. May you have similar needs feel free to pick up some code in the add-on (https://github.com/ubisoft/stampinfo).

Julien

**Comment by OtherRealms** [comment]
Hi julien,
I've tested compatibility and there were no issues. Its interesting to see such a different take on the ui. I was asked about stamping and meta data by a studio and PIL was my first thought, they were already using the compositor reluctantly, I think when the real-time compositor is introduced that will be a game changer. But I've avioded using dependencies in paid addons for fear of install issues, although PIL has been more reliable than some other packages when installing to Blender. Perhaps I could add integration to StampInfo

I noticed you had a percentage slider for resolution, you could use that for a progress bar? it would be editable by user but unlikely. Blender API doesn't have anything for a progress bar. I've made one simply using the progress percentage (find the frame numbers in std out) as the factor for row.split(factor = percentage/10) , and use a prop as a bar. I'm not sure how you're going about the render process, but you'll have to run the background render in a modal operator and force ui updates, otherwise you'll get a frozen ui.
![bar](https://user-images.githubusercontent.com/58406975/186571017-3009f4de-9c7a-43df-8319-dd2160b94459.JPG)
r
