### ISSUE TITLE
When having multiple Blender Scenes, Shot Manager names all the shots "-" in the new Scenes

### ISSUE THREAD

**Issue by pesjakves** [ubisoft/shotmanager#41]
****Infos on the context****
- Blender v 3.2.1
- Add-on version: 2.0.214
- OS: Win

**Describe the bug**
When creating a new Scene in the same Project (.blend file), the new shots cannot be renamed and their name is always "-".
Also, UI gets kind of confused and keeps the same Sequence name and has some shots from the previous scene but no camera linked to them as there is no camera in the new scene. 
Not sure if it is just a bug in the naming of the Shots but it would be nice to have the Shot Manager working in multiple Blender Scenes :) 

I have 2 suggestions:
- Either make the Sequence stay the same between Blender Scenes, Basically, Sequence = Blender Scene
- Or make a new Sequence (maybe add a Sequence list?), independent of the Blender Scenes and have the Shot List transfer between Blender Scenes

**Screenshots**
scene 1
![image](https://user-images.githubusercontent.com/53349108/185889437-893c2880-24d4-402c-986e-7e53b2488baf.png)

scene 2
![image](https://user-images.githubusercontent.com/53349108/185889336-9f59e435-b5d1-4063-ba3c-0570a2c80e2e.png)

**Comment by pesjakves** [comment]
otherwise, I love the addon! Thank you so much for making our production easier

**Comment by werwack** [comment]
Hi @pesjakves,
Thanks for reporting this issue.
Shot Manager is indeed perfectly able to work on files with multiple scenes. There is no relationship at all between scenes.

So far I have not been able to reproduce the bug. I created new scenes, new takes, new shots. The names of the shots are never "-" on my side and I am always able to rename then.
**Could you please share a more step by step repro process? Or a video maybe?**

At the moment there are no tools to copy a shot from a scene to another. That's on the roadmap, but not for so soon. If that sounds useful for you let me know.

Regarding the suggestion of having the sequence name based on the scene name it used to work like that at the beginning. We eventually changed that to provide more control on this name and to allow scene duplication (so that it was possible to have "variations" of the action while keeping the same sequence name. Not sure that's a very good practice but that was the idea.
Some improvements will be done soon on the notion of Project and on the content of the sequences. I'll think about this naming remark of yours.

**Comment by pesjakves** [comment]
Hi, I am sorry, I tried to reecord it but somehow it only recorded part of the screen :) But I hope you can see the result of creating a new scene in the video recording I attached :)[https://drive.google.com/file/d/1EWB3XHsfmcFOVSQpKaa6P496CIlpcGBx/view?usp=sharing](url)

**Comment by werwack** [comment]
Hi @pesjakves,
Thank you for the video. I got some clues from it but a few things are still unclear for me.

First of all, is there some sound in the video? For some reason I can't hear anything. Some live comment would be helpful :D

To me, if I understand your questions, there are 2 points:

**- What is the "negative time indicies" warning message?**
I'll try to improve the message. Basically it says that when the frames will be rendered there will be some of them with negative values, which is not supported by Blender. This is because you have activated the Projects Settings - which is great - and it them it is specified to use handles (= frames before and after the shot range, to provide some more pictures to the editing artist). But in the meantime your first shot starts at frame 1. So you you do 1 minus handle duration (which is 10 by default) you get frames with indices such as -9, -8, -7... -1.
To fix the issue either uncheck the use of handles, or put them at 1 (not so useful) or insert some time - like 20 frames for example - at frame 0 globaly in your scene (thanks to the Retimer tool, in the Features panel).

**- Why no shots are visible in the other scene?**
Well, here as you mentioned I miss some visuals. Apparently you expect to get the shots in the other scene right? It that is the case, well, Shot Manager is not working like that. The scenes are completely independent one from the others.

Does this help?
