### ISSUE TITLE
Doesn't install on the 3.2.0 version

### ISSUE THREAD

**Issue by sorciere000** [ubisoft/shotmanager#42]
**Infos on the context**

- Add-on version: 2.0
- Blender version, from installer or from zip:  3.2.0
- Blender was launched in Admin mode? 
- OS: windows 10 famille 21H1 en 64b
- Bug was also on previous versions YES with the 1.7

**Describe the bug**

I downloaded the "Ubisoft_ShotManager_V2-0-214.zip" 
In preference > addons > I search for the location. 
On the left bottom written in the info log : 
Modules Installed () from 'C:\\Users\\PC\\Downloads\\_T_BLENDER\\_SCRIPTS\\Ubisoft_ShotManager_V2-0-214.zip' into 'C:\\Users\\PC\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
But nothing else happens... 

I also tried with the "shotmanager-main.zip" 
Same thing

Thank you for your cool work ! I really look forward to try it in my workflow :)

**Comment by sorciere000** [comment]
tested on the 3.1 and the 3.2.2 same problem.. 

It's not the first time I encounter this problem on addon I want to install...

**Comment by Miatoo** [comment]
Same issue.
And could install successful for the beta version.

**Comment by werwack** [comment]
Hello @sorciere000, @Miatoo 

I just pushed a pre-release version with some bug fixes for the installation: https://github.com/ubisoft/shotmanager/releases/tag/v2.0.224
Can you try with this one please?

Also be sure to follow the installation steps, they are important: https://ubisoft-shotmanager.readthedocs.io/en/latest/getting-started/install.html
I also recommend to open the Blender System Console before checking the Install checkbox in the add-on Preferences panel, this in order to display all the output messages in case of trouble.

**Comment by Miatoo** [comment]
It works! Try on 3.2.2. Thank you so much!

**Comment by werwack** [comment]
Fix officially released in the latest version: [V2.0.225](https://github.com/ubisoft/shotmanager/releases).
Let me know if you still have some issues with this one.
