### ISSUE TITLE
A new bug appears and the file cannot be automatically saved

### ISSUE THREAD

**Issue by sanroot3** [ubisoft/shotmanager#48]
There is a new bug that the file cannot be automatically saved, and the automatic saving is set in the system preferences.

**Comment by werwack** [comment]
Hi Sanroot,
Can you elaborate? I cannot fix anything without more details.
Please fill the full "bug report" issue, with the version you are using, the Blender version, some repro steps.

Thank you

**Comment by sanroot3** [comment]
Blender did not report an error. I found that the original project file was damaged and could not be opened after the software crashed. I went to check the auto-save file and found that it was not saved. Later, I tested it with versions 3.3 and 3.2, and now it will not be automatically saved. It used to be. It is automatically saved, and no other new plugins have been installed recently.

**Comment by werwack** [comment]
Humm. Which version of Shot Manager are you using?

**Comment by sanroot3** [comment]
2.0.225

**Comment by werwack** [comment]
I ran some tests - with and without Shot Manager installed - on Blender 3.3.0 and did not found any unexpected behaviors.

So just to be sure: here is a good presentation of how the autosave works and where the recover file is:
https://irendering.net/how-to-use-autosave-to-recover-blender-files-from-crashes/

You may already be aware of that, but just in case: there is only 1 autosave file and it is not located near the working file. It can be opened from the main menu: File -> Recover -> Auto Save
On my side the last modification date of this file is consistent with the Preferences, so far.

My prod experience led me to adopt a more manual way of keeping a previous version of the file. I then prefer and recommend the use of the + button (right near the name of the saved file, in the Save As... dialog window) to increment the file name - at least up to when it is submitted on a production tracker.

I'll keep an eye on that weird behavior you are pointing out anyway, so that hopefully I can repro it on my side.
