### ISSUE TITLE
Rendering functionality not working, perhaps the addon didn't install properly. 

### ISSUE THREAD

**Issue by NausetJF** [ubisoft/shotmanager#51]
**Infos on the context**
- Add-on version: 2.1.32
- Blender version, from the installer or from zip: zip
- Blender was launched in Admin mode? running it as a superuser installs add-ons under root and not under my user account. 
- OS: Linux Mint 21 
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): I don't know 

**Describe the bug**
The addon spits out an error whenever I attempt to render the current shot or render all. 

**To Reproduce**
1. Go to 'Render Current or Render All'

**Expected behavior**
I expected the addon to install properly with all of its Python modules successfully installed, and for the rendering functionality to work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108027891/201497007-46b0ec41-a48f-4f2e-914c-aa65ee1babb6.png)
![image](https://user-images.githubusercontent.com/108027891/201497139-77c2f07b-378e-4619-badb-8191869bd110.png)
![image](https://user-images.githubusercontent.com/108027891/201497148-e54da4f6-24fb-40db-8f17-a5c6eef6c6e1.png)

**Additional context**
I have a feeling this could be because I cannot install this addon properly under Linux because running it as a superuser installs the addons under root and not under my user account. I've tried manually installing the modules using pip but that didn't seem to work. If that's not the case, is it a firewall issue?

**Comment by jatubi** [comment]
Hi @NausetJF 

So here is what is happening: the Python packaged named PIL has apparently not been able to be installed. It is required by StampInfo, which is the module of Shot Manager that is used to write the metadata onto the rendered images. For some reason there is a first bug here, that I fixed in the version provided below.

In the meantime I found a bug on Linux on the way the internet connection is checked. I also fixed it. Blindly I must say (we don't use Linux).

So can you please download this version and tell me if that changes something: https://we.tl/t-FdvmA0KquN
Also when you do the installation, be sure to launch Blender in Admin mode. Then relaunch it in normal mode.

It worth ck the firewall also, of course ;)
