### ISSUE TITLE
Blender 4.0 support

### ISSUE THREAD

**Issue by whurst121280** [ubisoft/shotmanager#63]
**Is your feature request related to a problem? Please describe.**
The problem is I'm not a coder and thus I am unable make the addon compatible myself.

**Describe the solution you'd like**
A hero, or group of heroes, to get this addon working in Blender 4.0.

**Describe alternatives you've considered**
Cry. Seriously, my alternative is to just cry because It seems this is a very untapped addon niche. You don't know you needed it until you have used it.

**Additional context**
I fully understand this addon is no longer in development and only being maintained. The fact that it is has worked across the wide amount of versions that it has worked for is unheard of for for an addon. This is just a hope an a prayer.

**Comment by Betti83771** [comment]
Now available! https://github.com/Betti83771/shotmanager_for_Blender4.1

**Comment by whurst121280** [comment]
Do you have a cape? If not do you need and/or want one? I will make that happen. It may or may only be a bed sheet but those make the best capes! You are a hero thank you!

**Comment by Betti83771** [comment]
> Do you have a cape? If not do you need and/or want one? I will make that happen. It may or may only be a bed sheet but those make the best capes! You are a hero thank you!

Thank you so much :) 

I forgot to update the .zip in the release page to the latest fix even though the repository is up to date. I just updated it, so please [re-download](https://github.com/Betti83771/shotmanager_for_Blender4.1/releases/download/v2.1.46/shotmanager_for_blender_4.1.zip) and reinstall! Else the render button might not work properly due to some changes in PIL.

Right now I am working on another branch for my studio, if it ends up being used in production there will be more fixes but probably on that branch.

Also the author is releasing a paid version of an [enhanced version of the addon](https://werwackfx.com/storyliner/doc/) he's working on right now, available for both Blender 3.3 LTS and Blender 4.

**Comment by whurst121280** [comment]
Story Liner looks super useful. Its just shooting for much more than what I need. This addon is also a bit over my specific needs, but checks all my boxes. It also keeps things fairly simple and to the point. I have a couple projects that are visual novel based so this addon really helps since it's a lot like story boarding/pre-vis. I'm not the best with straight up code, but visual scripting I pretty good with. I might have to look into making a simplified version for myself using serpens. Just to make dealing with camera markers or "scenes" easier. Either way just to have this working in Blender 4 is awesome! Thanks again!

**Comment by whurst121280** [comment]
Works!
